name: API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  newman-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run Newman tests with Docker
        run: |
          docker run -v ${{ github.workspace }}:/etc/newman \
          -t postman/newman:latest \
          run collection.json \
          --reporters cli,json \
          --reporter-json-export results.json
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: newman-results
          path: results.json
